require('lazy').setup({
  require 'plugins.autopairs',
  require 'plugins.blink-cmp',
  require 'plugins.bullets',
  require 'plugins.colorizer',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.cord',
  require 'plugins.debug',
  require 'plugins.dressing',
  require 'plugins.emmet',
  require 'plugins.flash',
  require 'plugins.fzf',
  require 'plugins.gitsigns',
  -- require 'plugins.gruvbox',
  require 'plugins.rosepine',
  require 'plugins.harpoon',
  require 'plugins.img-clip',
  -- require 'plugins.incline',
  require 'plugins.lazydev',
  require 'plugins.lint',
  require 'plugins.lsp-config',
  require 'plugins.lsp-rust',
  require 'plugins.lspsaga',
  require 'plugins.mason',
  require 'plugins.mini-starter',
  require 'plugins.mini-statusline',
  require 'plugins.mini',
  require 'plugins.neo-tree',
  require 'plugins.noice',
  require 'plugins.nvim-treesitter',
  require 'plugins.obsidian',
  require 'plugins.render-markdown',
  require 'plugins.sleuth',
  require 'plugins.snacks',
  require 'plugins.tailwind-tools',
  require 'plugins.todo-comments',
  require 'plugins.trouble',
  require 'plugins.ts-autotag',
  require 'plugins.typesctipt-tools',
  require 'plugins.wakatime',
  require 'plugins.which-key',
  require 'plugins.winshift',
}, {
  ui = {
    icons = {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})
