-- My keymaps
vim.keymap.set('n', '<leader>s', '<cmd>wall<CR>', { desc = 'Save all buffers' })
vim.keymap.set('n', '<C-a>', 'ggVG', { desc = 'Select all' })

vim.keymap.set('n', '<C-d>', '<C-d>zz', {})
vim.keymap.set('n', '<C-u>', '<C-u>zz', {})
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Move line down in Visual mode' })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Move line up in Visual mode' })
vim.keymap.set('n', 'n', 'nzz', {})
vim.keymap.set('n', 'N', 'Nzz', {})
vim.keymap.set('n', '*', '*zz', {})
vim.keymap.set('n', '#', '#zz', {})
vim.keymap.set('n', 'g*', 'g*zz', {})
vim.keymap.set('n', 'g#', 'g#zz', {})
vim.keymap.set('v', '<', '<g', {})
vim.keymap.set('v', '>', '>g', {})
vim.keymap.set('v', 'p', '"_dP', { desc = 'Paste without saving' })

vim.keymap.set({ 'n', 'x', 'o' }, 'H', '^', { desc = 'Go to start of line' })
vim.keymap.set({ 'n', 'x', 'o' }, 'L', 'g_', { desc = 'Go to end of line' })

vim.keymap.set('n', '<C-i>', '<C-o>', { desc = 'Replace goto next' })
vim.keymap.set('n', '<C-o>', '<C-i>', { desc = 'Replace goto prev' })
vim.keymap.set('n', '<esc>', '<cmd>noh<CR>', { silent = true, desc = 'Clear search' })

-- LazyVim shit keymaps
vim.keymap.del('n', '[b')
vim.keymap.del('n', ']b')
vim.keymap.del('n', '<leader>bb')
vim.keymap.del('n', '<leader>`')
vim.keymap.del('n', '<leader>bd')
vim.keymap.del('n', '<leader>bo')
vim.keymap.del('n', '<leader>bD')

vim.keymap.del('n', '<leader>e')

vim.keymap.del('n', '<leader>sa')
vim.keymap.del('n', '<leader>sb')
vim.keymap.del('n', '<leader>sc')
vim.keymap.del('n', '<leader>sC')
vim.keymap.del('n', '<leader>sd')
vim.keymap.del('n', '<leader>sD')
vim.keymap.del('n', '<leader>sg')
vim.keymap.del('n', '<leader>sG')
vim.keymap.del('n', '<leader>sh')
vim.keymap.del('n', '<leader>sH')
vim.keymap.del('n', '<leader>sj')
vim.keymap.del('n', '<leader>sk')
vim.keymap.del('n', '<leader>sl')
vim.keymap.del('n', '<leader>sm')
vim.keymap.del('n', '<leader>sM')
vim.keymap.del('n', '<leader>ss')
vim.keymap.del('n', '<leader>sS')
vim.keymap.del('n', '<leader>st')
vim.keymap.del('n', '<leader>sT')
vim.keymap.del('n', '<leader>sw')
vim.keymap.del('n', '<leader>sW')
vim.keymap.del('n', '<leader>s"')
vim.keymap.del('n', '<leader>sq')
vim.keymap.del('n', '<leader>sR')
vim.keymap.del('n', '<leader>s/')

vim.keymap.del('n', '<leader>K')
vim.keymap.del('n', '<leader>S')

vim.keymap.del('n', '<leader>be')

vim.keymap.del('n', '<leader>cl')
vim.keymap.del('n', '<leader>cd')
vim.keymap.del('n', '<leader>cf')
vim.keymap.del('n', '<leader>cF')
vim.keymap.del('n', '<leader>cs')

vim.keymap.del('n', '<leader>fb')
vim.keymap.del('n', '<leader>fc')
vim.keymap.del('n', '<leader>fF')
vim.keymap.del('n', '<leader>fg')
vim.keymap.del('n', '<leader>fr')
vim.keymap.del('n', '<leader>fR')
vim.keymap.del('n', '<leader>fn')
vim.keymap.del('n', '<leader>fe')
vim.keymap.del('n', '<leader>fE')
vim.keymap.del('n', '<leader>fT')

vim.keymap.del('n', '<leader>gg')
vim.keymap.del('n', '<leader>gY')
vim.keymap.del('n', '<leader>gL')

vim.keymap.del('n', '<leader><space>')
vim.keymap.del('n', '<leader>.')
vim.keymap.del('n', '<leader>/')
vim.keymap.del('n', '<leader>:')
vim.keymap.del('n', '<leader>,')
vim.keymap.del('n', '<leader>?')
vim.keymap.del('n', '<Tab>')
