vim.keymap.set('n', '<leader>i', '<cmd>TSToolsOrganizeImports<CR>', { desc = 'TS tools organize imports' })
vim.keymap.set('n', '<leader>s', '<cmd>wall<CR>', { desc = 'Save all buffers' })
vim.keymap.set('n', '<C-a>', 'ggVG', { desc = 'Select all' })

vim.keymap.set('n', '<C-d>', '<C-d>zz', {})
vim.keymap.set('n', '<C-u>', '<C-u>zz', {})
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Move line down in Visual mode' })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Move line up in Visual mode' })
vim.keymap.set('n', 'n', 'nzz', {})
vim.keymap.set('n', 'N', 'Nzz', {})
vim.keymap.set('n', '*', '*zz', {})
vim.keymap.set('n', '#', '#zz', {})
vim.keymap.set('n', 'g*', 'g*zz', {})
vim.keymap.set('n', 'g#', 'g#zz', {})
vim.keymap.set('v', '<', '<g', {})
vim.keymap.set('v', '>', '>g', {})
vim.keymap.set('v', 'p', '"_dP', { desc = 'Paste without saving' })

vim.keymap.set({ 'n', 'x', 'o' }, 'H', '^', { desc = 'Go to start of line' })
vim.keymap.set({ 'n', 'x', 'o' }, 'L', 'g_', { desc = 'Go to end of line' })

vim.keymap.set('n', '<C-i>', '<C-o>', { desc = 'Replace goto next' })
vim.keymap.set('n', '<C-o>', '<C-i>', { desc = 'Replace goto prev' })
vim.keymap.set('n', '<esc>', '<cmd>noh<CR>', { silent = true, desc = 'Clear search' })

vim.keymap.set('n', '<M-h>', '<C-w>h', { desc = 'Moving between windows' })
vim.keymap.set('n', '<M-j>', '<C-w>j', { desc = 'Moving between windows' })
vim.keymap.set('n', '<M-k>', '<C-w>k', { desc = 'Moving between windows' })
vim.keymap.set('n', '<M-l>', '<C-w>l', { desc = 'Moving between windows' })

vim.keymap.set('n', '<M-=>', '<C-w>+', { desc = 'Resize window +' })
vim.keymap.set('n', '<M-->', '<C-w>-', { desc = 'Resize window -' })
vim.keymap.set('n', '<M-,>', '<C-w>>', { desc = 'Resize window >' })
vim.keymap.set('n', '<M-.>', '<C-w><', { desc = 'Resize window <' })

vim.keymap.set('n', '<leader>sh', '<cmd>split<CR>', { desc = 'Open split horizontal window' })
vim.keymap.set('n', '<leader>sv', '<cmd>vsplit<CR>', { desc = 'Open split vertical window' })
