require('lazy').setup({
  { import = 'plugins.appearance' },
  { import = 'plugins.cmp' },
  { import = 'plugins.editing' },
  { import = 'plugins.formatting' },
  { import = 'plugins.git' },
  { import = 'plugins.lsp' },
  { import = 'plugins.mini' },
  { import = 'plugins.navigation' },
  { import = 'plugins.productivity' },
  { import = 'plugins.syntax' },
}, {
  ui = {
    icons = {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})
